language: common-lisp

env:
  matrix:
#    - LISP=abcl # lisp-interface-library won't build
    - LISP=allegro
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
#    - LISP=clisp # lisp-interface-library won't build
#    - LISP=clisp32 # lisp-interface-library won't build
#    - LISP=cmucl
#    - LISP=ecl # stalls while building test package

install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi

script:
  - cl -e '(in-package :cl-user)'
       -e '(setf *print-circle* t)'
       -e '(ql:quickload (list :cl-jsync :cl-jsync-test))'
       -e '(let ((*debugger-hook*
                  (lambda (c h)
                    (declare (ignore c h))
                    (uiop:quit -1))))
             (cl-jsync-test:test-all))'
